apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: lrucache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: priyanshjain21/lru_assignment_backend:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: lrucache
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend
