apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: lrucache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
      - name: postgres-exporter
        image: prometheuscommunity/postgres-exporter:latest
        ports:
        - containerPort: 9187
        env:
        - name: DATA_SOURCE_NAME
          value: "postgresql://postgresuser1:Priyansh@21@postgres-service:5432/?sslmode=disable"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter-service
  namespace: lrucache
spec:
  ports:
  - port: 9187
    targetPort: 9187
  selector:
    app: postgres-exporter
