apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: lrucache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgresuser1"
        - name: POSTGRES_PASSWORD
          value: "Priyansh@21"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: lrucache
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
