apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: lrucache
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'backend'
        static_configs:
          - targets: ['backend-service.lrucache.svc.cluster.local:8080']
      - job_name: 'postgres-exporter'
        static_configs:
          - targets: ['postgres-exporter-service.lrucache.svc.cluster.local:9187']
